# Copyright 2020 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: ok-

# Labels to add to all resources and selectors.
commonLabels:
    app.kubernetes.io/name: "withcrd-ok"
