# Copyright 2020 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

configurations:
- kustomizeconfig.yaml
images:
- name: kube-app-manager
  newName: quay.io/kubernetes-sigs/kube-app-manager
  newTag: v0.8.3
