# Copyright 2020 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- application.yaml
- configmap.yaml
- deployment.yaml
- job.yaml
- service.yaml
- testcr1.yaml
- testcr2.yaml
- testcr3.yaml
