# Copyright 2020 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: websvc
  labels:
    app.kubernetes.io/version: "3"
    app.kubernetes.io/component: "test-svc"
    app.kubernetes.io/tier: "frontend"
spec:
  ports:
  - port: 80
  selector:
    app.kubernetes.io/component: "test-webserver"
  clusterIP: None
