# Copyright 2020 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0

# permissions to do edit applications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: application-editor-role
rules:
- apiGroups:
  - app.k8s.io
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.k8s.io
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
