# Copyright 2020 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: nok-

# Labels to add to all resources and selectors.
commonLabels:
    app.kubernetes.io/name: "withcrd-nok"

patchesStrategicMerge:
- |-
  apiVersion: app.k8s.io/v1beta1
  kind: Application
  metadata:
    name: withcrd
  spec:
    selector:
      matchLabels:
        app.kubernetes.io/name: "withcrd-nok"

images:
  - name: gcr.io/google-samples/node-hello
    newName: badimage
    newTag: badtag
